version: "3.9"
services:
    webapp:
        build:
            context: .
        env_file: .env
        ports:
            - 8080:80
        volumes:
            - ./public_html:/var/www/ratemynugget/public_html

