name: Build & Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Build, tag and push image to Amazon ECR
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/ratemynugget:${{ github.sha }}

      - uses: actions/checkout@v2
      
      - name: Update manifest with dynamic values
        run: |
          sed -i  's/tag/${{ github.sha }}/g' ./kube/schema.yaml
          sed -i  's/mongosecret/${{ secrets.MONGO }}/g' ./kube/schema.yaml
          cat ./kube/schema.yaml
          
      - name: Setup Kubectl & deploy
        run: |
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 --decode > /tmp/config
          export KUBECONFIG=/tmp/config
          kubectl apply -f ./kube/schema.yaml